- name: Check if destination directory exists
  stat:
    path: /opt/rovi/ids-service
  register: dir_status

- name: Create destination directory if not exists
  file:
    path: /opt/rovi/ids-service
    state: directory
    mode: '0755'
  when: not dir_status.stat.exists

- name: Download artifact from JFrog
  get_url:
    url: "http://10.28.218.243:8082/artifactory/my-repo-local/maven-demo-1.0-SNAPSHOT.jar"
    dest: "/opt/rovi/ids-service/"
    url_username: "{{ jfrog_user }}"
    url_password: "{{ jfrog_password }}"
    mode: '0755'


- name: Stop existing app if running
  shell: |
    if pgrep -f myapp.jar > /dev/null; then
      pkill -f myapp.jar
    fi
  args:
    executable: /bin/bash
  register: stop_result
  failed_when: false
  changed_when: stop_result.rc == 0
  
- name: Ensure log directory exists
  file:
    path: /opt/rovi/log/metrics-processor
    state: directory
    mode: '0755'

- name: Start app if not running
  shell: |
    if ! pgrep -f maven-demo-1.0-SNAPSHOT.jar > /dev/null; then
      nohup java -jar /opt/rovi/ids-service/maven-demo-1.0-SNAPSHOT.jar > /opt/rovi/ids-service/app.log 2>&1 &
    fi
  args:
    chdir: "/opt/rovi/ids-service"
    executable: /bin/bash
  register: start_result
  failed_when: false
  changed_when: start_result.rc == 0


